app : 
  name : "go-huberi"
  version : "1.0.0"
  author : "Aldi Syah Putra"

web : 
  port : 3000
  prefork : false

log :
  level : 6

database : 
  username : "root"
  password : ""
  host : "localhost"
  port : 3306
  name : "huberi"
  pool:
    idle: 10
    max: 100
    lifetime: 300